apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: | 
    events {}
    http {
      server {
        listen 80;
        location / {
            proxy_pass http://flask-app:5500;
        }
        location /hello {
    return 200 "Hello World";
        }
      }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx # selector for service should be the same 
spec:
  volumes:
  - name: nginx-volume
  configMap:
    name: nginx-config
  containers:
  - name: nginx
    image: nginx:latest # dockerhub
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nginx-volume
      mountPath: /etc/nginx/
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80